{% set name = "lstmcpipe" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lstmcpipe-{{ version }}.tar.gz
  sha256: 47c68b268c6ade8937902ea274a4acb67bdb8b4abc8585660241997da79f824a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - lstmcpipe = lstmcpipe.lstmcpipe_start:main
    - lstmcpipe_plot_models_importance = lstmcpipe.plots.plot_models_importance:main
    - lstmcpipe_plot_irfs = lstmcpipe.plots.plot_irfs:main
    - lstmcpipe_hiperta_r0_to_dl1lstchain = lstmcpipe.hiperta.hiperta_r0_to_dl1lstchain:main
    - lstmcpipe_dl2_to_sensitivity = lstmcpipe.scripts.script_dl2_to_sensitivity:main
    - lstmcpipe_train_test_split = lstmcpipe.scripts.script_train_test_splitting:main
    - lstmcpipe_lst_core_r0_dl1 = lstmcpipe.scripts.script_batch_filelist_lst:main
    - lstmcpipe_lst_core_dl1ab = lstmcpipe.scripts.script_batch_filelist_lst_dl1ab:main
    - lstmcpipe_cta_core_r0_dl1 = lstmcpipe.scripts.script_batch_filelist_cta:main
    - lstmcpipe_rta_core_r0_dl1 = lstmcpipe.scripts.script_batch_filelist_rta:main
    - lstmcpipe_compare_irfs = lstmcpipe.scripts.script_compare_irfs:main
    - lstmcpipe_validate_config = lstmcpipe.scripts.script_lstmcpipe_validate_config:main
    - lstmcpipe_generate_config = lstmcpipe.scripts.lstmcpipe_generate_config:main
    - lstmcpipe_generate_nsb_levels_configs = lstmcpipe.scripts.generate_nsb_levels_configs:main

requirements:
  host:
    - python >=3.9
    - setuptools-scm <8.0
    - pip
  run:
    - python >=3.9
    - lstchain >=0.9.0
    - numpy
    - astropy
    - ctaplot >=0.5
    - pyirf >=0.4
    - matplotlib-base
    - pytest
    - ruamel.yaml >=0.17
    - setuptools-scm <8.0
    - deepdiff
    - ctapipe
    - pytables
    - tqdm
    - pandas

test:
  imports:
    - lstmcpipe
  commands:
    - pip check
    - lstmcpipe --help
    - lstmcpipe_plot_models_importance --help
    - lstmcpipe_plot_irfs --help
    - lstmcpipe_hiperta_r0_to_dl1lstchain --help
    - lstmcpipe_dl2_to_sensitivity --help
    - lstmcpipe_train_test_split --help
    - lstmcpipe_lst_core_r0_dl1 --help
    - lstmcpipe_lst_core_dl1ab --help
    - lstmcpipe_cta_core_r0_dl1 --help
    - lstmcpipe_rta_core_r0_dl1 --help
    - lstmcpipe_compare_irfs --help
    - lstmcpipe_validate_config --help
    - lstmcpipe_generate_config --help
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/lstmcpipe
  summary: Scripts to ease the reduction of MC data on the LST cluster at La Palma. With this package, the analysis/creation of R1/DL0/DL1/DL2/IRFs can be orchestrated.
  license: MIT
  license_file: license.rst
  doc_url: https://cta-observatory.github.io/lstmcpipe/
  dev_url: https://github.com/cta-observatory/lstmcpipe

extra:
  recipe-maintainers:
    - vuillaut
